"""add image_url to properties

Revision ID: 04acbcb5c06b
Revises: 2ecea7d78926
Create Date: 2026-01-18 21:32:36.065782

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04acbcb5c06b"
down_revision: str | Sequence[str] | None = "2ecea7d78926"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties", sa.Column("image_url", sa.String(length=2048), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "image_url")
    # ### end Alembic commands ###
