"""Add properties table

Revision ID: 2ecea7d78926
Revises:
Create Date: 2026-01-17 23:35:08.211506

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.database.enum import Enum

# revision identifiers, used by Alembic.
revision: str = "2ecea7d78926"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "properties",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "source",
            Enum("estitor", "realitica", name="propertysource"),
            nullable=False,
        ),
        sa.Column("link", sa.String(length=2048), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=512), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "property_type",
            Enum(
                "Stan",
                "Kuća",
                "Garsonjera",
                "Apartman",
                "Vikendica",
                "Poslovni prostor",
                "Zemljište",
                "Unknown",
                name="propertytype",
            ),
            nullable=True,
        ),
        sa.Column("price_raw", sa.String(length=255), nullable=False),
        sa.Column("price_eur", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("area_raw", sa.String(length=255), nullable=True),
        sa.Column("area_sqm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("rooms_raw", sa.String(length=255), nullable=True),
        sa.Column("rooms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_properties")),
        sa.UniqueConstraint("link", name=op.f("uq_properties_link")),
    )
    op.create_index(
        "ix_properties_area_rooms", "properties", ["area_sqm", "rooms"], unique=False
    )
    op.create_index(
        op.f("ix_properties_area_sqm"), "properties", ["area_sqm"], unique=False
    )
    op.create_index(op.f("ix_properties_city"), "properties", ["city"], unique=False)
    op.create_index(
        "ix_properties_city_price", "properties", ["city", "price_eur"], unique=False
    )
    op.create_index(
        "ix_properties_city_type", "properties", ["city", "property_type"], unique=False
    )
    op.create_index(
        op.f("ix_properties_created_at"), "properties", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_properties_price_eur"), "properties", ["price_eur"], unique=False
    )
    op.create_index(
        op.f("ix_properties_property_type"),
        "properties",
        ["property_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_properties_property_type"), table_name="properties")
    op.drop_index(op.f("ix_properties_price_eur"), table_name="properties")
    op.drop_index(op.f("ix_properties_created_at"), table_name="properties")
    op.drop_index("ix_properties_city_type", table_name="properties")
    op.drop_index("ix_properties_city_price", table_name="properties")
    op.drop_index(op.f("ix_properties_city"), table_name="properties")
    op.drop_index(op.f("ix_properties_area_sqm"), table_name="properties")
    op.drop_index("ix_properties_area_rooms", table_name="properties")
    op.drop_table("properties")
    Enum("estitor", "realitica", name="propertysource").drop(op.get_bind())
    Enum(
        "Stan",
        "Kuća",
        "Garsonjera",
        "Apartman",
        "Vikendica",
        "Poslovni prostor",
        "Zemljište",
        "Unknown",
        name="propertytype",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
